### ISSUE TITLE
React, error : invalid hook call

### ISSUE THREAD

**Issue by palix-jc** [mdbootstrap/mdb-react-ui-kit#149] opened 2021-05-06 14:40 UTC
Hello,

I recently got this error with a fresh install of a new react app : 
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app

if i do a npm -ls react i get : 
+-- mdbreact@5.0.2
| `-- UNMET PEER DEPENDENCY react@17.0.1
`-- react@17.0.2

npm ERR! peer dep missing: react@^16.3.0, required by @material-ui/core@3.9.3
npm ERR! peer dep missing: react@0.14.x || ^15.0.0 || ^16.0.0, required by focus-trap-react@6.0.0
npm ERR! peer dep missing: react@^16.3.0, required by material-ui-pickers@2.2.4
npm ERR! peer dep missing: react@^0.14.0 || ^15.0.0 || ^16.0.0-beta || ^16.0.0, required by react-chartjs-2@2.9.0
npm ERR! peer dep missing: react@^16.x, required by react-image-lightbox@5.1.1
npm ERR! peer dep missing: react@^15.5.4 || ^16.0.0, required by react-scroll@1.7.16

if i do a npm -ls react-dom i get : 
+-- mdbreact@5.0.2
| `-- UNMET PEER DEPENDENCY react-dom@17.0.1
`-- react-dom@17.0.2

npm ERR! peer dep missing: react-dom@^16.3.0, required by @material-ui/core@3.9.3
npm ERR! peer dep missing: react-dom@0.14.x || ^15.0.0 || ^16.0.0, required by focus-trap-react@6.0.0
npm ERR! peer dep missing: react-dom@^16.3.0, required by material-ui-pickers@2.2.4
npm ERR! peer dep missing: react-dom@^0.14.0 || ^15.0.0 || ^16.0.0-beta || ^16.0.0, required by react-chartjs-2@2.9.0
npm ERR! peer dep missing: react-dom@^16.x, required by react-image-lightbox@5.1.1
npm ERR! peer dep missing: react-dom@^15.5.4 || ^16.0.0, required by react-scroll@1.7.16

My dependencies in my package.json is : 
"dependencies": {
    "@testing-library/jest-dom": "^5.12.0",
    "@testing-library/react": "^11.2.6",
    "@testing-library/user-event": "^12.8.3",
    "mdbreact": "^5.0.2",
    "react": "^17.0.2",
    "react-bootstrap": "^1.5.2",
    "react-dom": "^17.0.2",
    "react-scripts": "4.0.3",
    "sweetalert2": "^10.16.7",
    "web-vitals": "^1.1.2"
  },
  
My index.js, like i said fresh install and just put this code :
` import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import {MDBBtn} from "mdbreact";

import '@fortawesome/fontawesome-free/css/all.min.css';
import 'bootstrap-css-only/css/bootstrap.min.css';
import 'mdbreact/dist/css/mdb.css';

ReactDOM.render(
  <React.StrictMode>
    Hello world
    <MDBBtn 
        type={"button"}
        gradient={"aqua"}
        >
        bouton test
    </MDBBtn>
  </React.StrictMode>,
  document.getElementById('root')
);
`

thanks for you help

**Comment by iserranoe** [comment] 2021-06-03 09:07
I have the same problem with the code: 

```
import './App.css';
import { 
  MDBContainer, 
  MDBRow, 
  MDBCol, 
  MDBInput, 
  MDBBtn 
} from 'mdbreact';

function App() {
  return (
    <MDBContainer>
      <MDBRow>
        <MDBCol md="6">
          <form>
            <p 
              className="h5 text-center mb-4">
                Sign in
            </p>
            <div className="grey-text">
              <MDBInput label="Type your email" icon="envelope" group type="email" validate error="wrong"
                success="right" />
              <MDBInput label="Type your password" icon="lock" group type="password" validate />
            </div>
            <div className="text-center">
              <MDBBtn
                readOnly
              >
                Login
              </MDBBtn>
            </div>
          </form>
        </MDBCol>
      </MDBRow>
    </MDBContainer>
  );
}

export default App;

```
And same dependencies:
```
"dependencies": {
    "@testing-library/jest-dom": "^5.12.0",
    "@testing-library/react": "^11.2.7",
    "@testing-library/user-event": "^12.8.3",
    "mdbootstrap": "^4.19.2",
    "mdbreact": "^5.0.2",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "4.0.3",
    "save": "^2.4.0",
    "web-vitals": "^1.1.2"
  },
```
The problematic component here is MDBBtn, when removing it or using standar `<button>` component, the problem is solved. 

**PS**

This is the error, by the way:
```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
./src/index.js/<
src/index.js:12

   9 | import App from './App';
  10 | //import reportWebVitals from './reportWebVitals';
  11 | 
> 12 | ReactDOM.render(
  13 |   <React.StrictMode>
  14 |     <App />
  15 |   </React.StrictMode>,

./src/index.js
http://xxx:3000/static/js/main.chunk.js:543:30
__webpack_require__
/home/ines/panelbim/frontend/webpack/bootstrap:851

  848 | 
  849 | __webpack_require__.$Refresh$.init();
  850 | try {
> 851 | 	modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  852 | } finally {
  853 | 	__webpack_require__.$Refresh$.cleanup(moduleId);
  854 | }

fn
/home/ines/panelbim/frontend/webpack/bootstrap:150

  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {

1
http://xxx:3000/static/js/main.chunk.js:557:18
__webpack_require__
/home/ines/panelbim/frontend/webpack/bootstrap:851

  848 | 
  849 | __webpack_require__.$Refresh$.init();
  850 | try {
> 851 | 	modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  852 | } finally {
  853 | 	__webpack_require__.$Refresh$.cleanup(moduleId);
  854 | }

checkDeferredModules
/home/ines/panelbim/frontend/webpack/bootstrap:45

  42 | 	}
  43 | 	if(fulfilled) {
  44 | 		deferredModules.splice(i--, 1);
> 45 | 		result = __webpack_require__(__webpack_require__.s = deferredModule[0]);
     | ^  46 | 	}
  47 | }
  48 | 

webpackJsonpCallback
/home/ines/panelbim/frontend/webpack/bootstrap:32

  29 | 	deferredModules.push.apply(deferredModules, executeModules || []);
  30 | 
  31 | 	// run deferred modules when all chunks ready
> 32 | 	return checkDeferredModules();
     | ^  33 | };
  34 | function checkDeferredModules() {
  35 | 	var result;

(anonymous function)
http://xxx:3000/static/js/main.chunk.js:1:69
```

**Comment by iserranoe** [comment] 2021-06-08 15:28
It is working fine if I downgrade mdbreact to 4.27.0 and react and react-dom to 16.14.0: 
```
"dependencies": {
    "mdbreact": "^4.27.0",
    "react": "^16.14.0",
    "react-dom": "^16.14.0",
    "react-scripts": "^4.0.3",
    "web-vitals": "^2.0.1"
  },
```
**PS**
Any news about this? This is not the best solution as I'd like to update react someday

**Comment by krzysiu-w** [comment] 2021-07-01 12:21
Hi!

React 17 provided some crucial changes and we are not able to fix that without changing a repository structure right now. Anyway - there are some solutions to fix that:

1. We highly recommend using MDB5 instead of MDB4.
2. Downgrade the mdbreact package to v4.27.0
3. Clone this repository or download a .zip package as a core for your project
4. If you have to create an application with Create-react-app - remove "react" and "react-dom" dependencies from the package.json file. Then install mdbreact. These two dependencies will be installed with our package, so react won't install twice and everything should work without errors :)

**Closed as completed by krzysiu-w** 2021-07-01 12:21 UTC

**Comment by iserranoe** [comment] 2021-11-11 13:53
I found another solution to this problem that is working for me so far. In my case, I had the problem with the `<MDBBtn>` component. What I did was to use the basic html button with `className = 'btn'`: 
```
<button className ='btn'>
</button>
```
